import type { Metadata } from "next"
import { Inter } from "next/font/google"
import ProviderChakra from "@/components/Providers/ProviderChakra"
import ReduxProvider from "@/components/Providers/ReduxProvider"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ReduxProvider>
			<html lang="en">
				<body className={inter.className}>
					<ProviderChakra>{children}</ProviderChakra>
				</body>
			</html>
		</ReduxProvider>
	)
}
