import type { Metadata } from "next"
import { Inter } from "next/font/google"
import ProviderChakra from "@/components/Providers/ProviderChakra"
import ReduxProvider from "@/components/Providers/ReduxProvider"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server"
import "../globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const LocaleLayout = async ({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) => {
	const messages = await getMessages()

	return (
		<ReduxProvider>
			<html lang={locale}>
				<body className={inter.className}>
					<NextIntlClientProvider messages={messages}>
						<ProviderChakra>{children}</ProviderChakra>
					</NextIntlClientProvider>
				</body>
			</html>
		</ReduxProvider>
	)
}

export default LocaleLayout
